language: go

# Setup database services required during tests.
services:
  - redis-server

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  - GO111MODULE=on

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
  - "1.10"

# Only clone the most recent commit.
git:
  depth: 1

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled
